/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FIASCo.Client;
using FIASCo.Api;
// uncomment below to import models
//using FIASCo.Model;

namespace FIASCo.Test.Api
{
    /// <summary>
    ///  Class for testing AddressInfoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AddressInfoApiTests : IDisposable
    {
        private AddressInfoApi instance;

        public AddressInfoApiTests()
        {
            instance = new AddressInfoApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressInfoApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AddressInfoApi
            //Assert.IsType<AddressInfoApi>(instance);
        }

        /// <summary>
        /// Test ApiSpasV20GetAddressItemByCadastralNumberGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetAddressItemByCadastralNumberGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cadastralNumber = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20GetAddressItemByCadastralNumberGet(cadastralNumber, addressType);
            //Assert.IsType<AddressesResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetAddressItemByGuidGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetAddressItemByGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? objectGuid = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20GetAddressItemByGuidGet(objectGuid, addressType);
            //Assert.IsType<AddressesResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetAddressItemByIdGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetAddressItemByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? objectId = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20GetAddressItemByIdGet(objectId, addressType);
            //Assert.IsType<AddressesResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetAddressItemsPost
        /// </summary>
        [Fact]
        public void ApiSpasV20GetAddressItemsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FilterObject filterObject = null;
            //var response = instance.ApiSpasV20GetAddressItemsPost(filterObject);
            //Assert.IsType<AddressesResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetDetailsGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetDetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? objectId = null;
            //var response = instance.ApiSpasV20GetDetailsGet(objectId);
            //Assert.IsType<AddressDetailsResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetFiasObjectTypesGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetFiasObjectTypesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiSpasV20GetFiasObjectTypesGet();
            //Assert.IsType<FiasTypesResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetRegionsGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetRegionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiSpasV20GetRegionsGet();
            //Assert.IsType<AddressesResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20HasDescendantsGet
        /// </summary>
        [Fact]
        public void ApiSpasV20HasDescendantsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? parent = null;
            //int? upToLevel = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20HasDescendantsGet(parent, upToLevel, addressType);
            //Assert.IsType<CheckResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20IsDescendantGet
        /// </summary>
        [Fact]
        public void ApiSpasV20IsDescendantGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? ancestor = null;
            //long? descendant = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20IsDescendantGet(ancestor, descendant, addressType);
            //Assert.IsType<CheckResult>(response);
        }
    }
}
