/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FIASCo.Client;
using FIASCo.Api;
// uncomment below to import models
//using FIASCo.Model;

namespace FIASCo.Test.Api
{
    /// <summary>
    ///  Class for testing NoticeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NoticeApiTests : IDisposable
    {
        private NoticeApi instance;

        public NoticeApiTests()
        {
            instance = new NoticeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NoticeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NoticeApi
            //Assert.IsType<NoticeApi>(instance);
        }

        /// <summary>
        /// Test ApiSpasV20AddNoticePost
        /// </summary>
        [Fact]
        public void ApiSpasV20AddNoticePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Notice notice = null;
            //var response = instance.ApiSpasV20AddNoticePost(notice);
            //Assert.IsType<AddNoticeResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetNoticeItemsPost
        /// </summary>
        [Fact]
        public void ApiSpasV20GetNoticeItemsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NoticeFilterObject noticeFilterObject = null;
            //var response = instance.ApiSpasV20GetNoticeItemsPost(noticeFilterObject);
            //Assert.IsType<NoticeItemsResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20GetNoticeStatusGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetNoticeStatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.ApiSpasV20GetNoticeStatusGet(id);
            //Assert.IsType<GetNoticeStatusResult>(response);
        }
    }
}
