/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FIASCo.Client;
using FIASCo.Api;
// uncomment below to import models
//using FIASCo.Model;

namespace FIASCo.Test.Api
{
    /// <summary>
    ///  Class for testing SearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SearchApiTests : IDisposable
    {
        private SearchApi instance;

        public SearchApiTests()
        {
            instance = new SearchApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SearchApi
            //Assert.IsType<SearchApi>(instance);
        }

        /// <summary>
        /// Test ApiSpasV20GetAddressHintGet
        /// </summary>
        [Fact]
        public void ApiSpasV20GetAddressHintGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchString = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20GetAddressHintGet(searchString, addressType);
            //Assert.IsType<HintResult>(response);
        }

        /// <summary>
        /// Test ApiSpasV20SearchAddressItemsGet
        /// </summary>
        [Fact]
        public void ApiSpasV20SearchAddressItemsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchString = null;
            //AddressType? addressType = null;
            //var response = instance.ApiSpasV20SearchAddressItemsGet(searchString, addressType);
            //Assert.IsType<AddressesResult>(response);
        }
    }
}
