/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddConversionDataInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddConversionDataInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddConversionDataInput
        //private AddConversionDataInput instance;

        public AddConversionDataInputTests()
        {
            // TODO uncomment below to create an instance of AddConversionDataInput
            //instance = new AddConversionDataInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddConversionDataInput
        /// </summary>
        [Fact]
        public void AddConversionDataInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddConversionDataInput
            //Assert.IsType<AddConversionDataInput>(instance);
        }


        /// <summary>
        /// Test the property 'TaskGuid'
        /// </summary>
        [Fact]
        public void TaskGuidTest()
        {
            // TODO unit test for the property 'TaskGuid'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
