/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddNoticeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddNoticeResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddNoticeResult
        //private AddNoticeResult instance;

        public AddNoticeResultTests()
        {
            // TODO uncomment below to create an instance of AddNoticeResult
            //instance = new AddNoticeResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddNoticeResult
        /// </summary>
        [Fact]
        public void AddNoticeResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddNoticeResult
            //Assert.IsType<AddNoticeResult>(instance);
        }


        /// <summary>
        /// Test the property 'NoticeId'
        /// </summary>
        [Fact]
        public void NoticeIdTest()
        {
            // TODO unit test for the property 'NoticeId'
        }

    }

}
