/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddressDetailsResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressDetailsResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressDetailsResult
        //private AddressDetailsResult instance;

        public AddressDetailsResultTests()
        {
            // TODO uncomment below to create an instance of AddressDetailsResult
            //instance = new AddressDetailsResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressDetailsResult
        /// </summary>
        [Fact]
        public void AddressDetailsResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressDetailsResult
            //Assert.IsType<AddressDetailsResult>(instance);
        }


        /// <summary>
        /// Test the property 'AddressDetails'
        /// </summary>
        [Fact]
        public void AddressDetailsTest()
        {
            // TODO unit test for the property 'AddressDetails'
        }

    }

}
