/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddressLevel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressLevelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressLevel
        //private AddressLevel instance;

        public AddressLevelTests()
        {
            // TODO uncomment below to create an instance of AddressLevel
            //instance = new AddressLevel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressLevel
        /// </summary>
        [Fact]
        public void AddressLevelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressLevel
            //Assert.IsType<AddressLevel>(instance);
        }



    }

}
