/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddressPart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressPartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressPart
        //private AddressPart instance;

        public AddressPartTests()
        {
            // TODO uncomment below to create an instance of AddressPart
            //instance = new AddressPart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressPart
        /// </summary>
        [Fact]
        public void AddressPartInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressPart
            //Assert.IsType<AddressPart>(instance);
        }


        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Fact]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'ObjectLevelId'
        /// </summary>
        [Fact]
        public void ObjectLevelIdTest()
        {
            // TODO unit test for the property 'ObjectLevelId'
        }
        /// <summary>
        /// Test the property 'ObjectGuid'
        /// </summary>
        [Fact]
        public void ObjectGuidTest()
        {
            // TODO unit test for the property 'ObjectGuid'
        }
        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Fact]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'FullNameShort'
        /// </summary>
        [Fact]
        public void FullNameShortTest()
        {
            // TODO unit test for the property 'FullNameShort'
        }

    }

}
