/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddressObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressObject
        //private AddressObject instance;

        public AddressObjectTests()
        {
            // TODO uncomment below to create an instance of AddressObject
            //instance = new AddressObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressObject
        /// </summary>
        [Fact]
        public void AddressObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressObject
            //Assert.IsType<AddressObject>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Fact]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }

    }

}
