/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddressDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressDetails
        //private AddressDetails instance;

        public AddressDetailsTests()
        {
            // TODO uncomment below to create an instance of AddressDetails
            //instance = new AddressDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressDetails
        /// </summary>
        [Fact]
        public void AddressDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressDetails
            //Assert.IsType<AddressDetails>(instance);
        }


        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'IfnsUl'
        /// </summary>
        [Fact]
        public void IfnsUlTest()
        {
            // TODO unit test for the property 'IfnsUl'
        }
        /// <summary>
        /// Test the property 'IfnsFl'
        /// </summary>
        [Fact]
        public void IfnsFlTest()
        {
            // TODO unit test for the property 'IfnsFl'
        }
        /// <summary>
        /// Test the property 'IfnsTul'
        /// </summary>
        [Fact]
        public void IfnsTulTest()
        {
            // TODO unit test for the property 'IfnsTul'
        }
        /// <summary>
        /// Test the property 'IfnsTfl'
        /// </summary>
        [Fact]
        public void IfnsTflTest()
        {
            // TODO unit test for the property 'IfnsTfl'
        }
        /// <summary>
        /// Test the property 'Okato'
        /// </summary>
        [Fact]
        public void OkatoTest()
        {
            // TODO unit test for the property 'Okato'
        }
        /// <summary>
        /// Test the property 'Oktmo'
        /// </summary>
        [Fact]
        public void OktmoTest()
        {
            // TODO unit test for the property 'Oktmo'
        }
        /// <summary>
        /// Test the property 'KladrCode'
        /// </summary>
        [Fact]
        public void KladrCodeTest()
        {
            // TODO unit test for the property 'KladrCode'
        }
        /// <summary>
        /// Test the property 'CadastralNumber'
        /// </summary>
        [Fact]
        public void CadastralNumberTest()
        {
            // TODO unit test for the property 'CadastralNumber'
        }
        /// <summary>
        /// Test the property 'ApartBuilding'
        /// </summary>
        [Fact]
        public void ApartBuildingTest()
        {
            // TODO unit test for the property 'ApartBuilding'
        }
        /// <summary>
        /// Test the property 'RemoveCadastr'
        /// </summary>
        [Fact]
        public void RemoveCadastrTest()
        {
            // TODO unit test for the property 'RemoveCadastr'
        }
        /// <summary>
        /// Test the property 'OktmoBudget'
        /// </summary>
        [Fact]
        public void OktmoBudgetTest()
        {
            // TODO unit test for the property 'OktmoBudget'
        }

    }

}
