/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing AddressItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressItem
        //private AddressItem instance;

        public AddressItemTests()
        {
            // TODO uncomment below to create an instance of AddressItem
            //instance = new AddressItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressItem
        /// </summary>
        [Fact]
        public void AddressItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressItem
            //Assert.IsType<AddressItem>(instance);
        }


        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Fact]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'ObjectLevelId'
        /// </summary>
        [Fact]
        public void ObjectLevelIdTest()
        {
            // TODO unit test for the property 'ObjectLevelId'
        }
        /// <summary>
        /// Test the property 'OperationTypeId'
        /// </summary>
        [Fact]
        public void OperationTypeIdTest()
        {
            // TODO unit test for the property 'OperationTypeId'
        }
        /// <summary>
        /// Test the property 'ObjectGuid'
        /// </summary>
        [Fact]
        public void ObjectGuidTest()
        {
            // TODO unit test for the property 'ObjectGuid'
        }
        /// <summary>
        /// Test the property 'AddressType'
        /// </summary>
        [Fact]
        public void AddressTypeTest()
        {
            // TODO unit test for the property 'AddressType'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'RegionCode'
        /// </summary>
        [Fact]
        public void RegionCodeTest()
        {
            // TODO unit test for the property 'RegionCode'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'AddressDetails'
        /// </summary>
        [Fact]
        public void AddressDetailsTest()
        {
            // TODO unit test for the property 'AddressDetails'
        }
        /// <summary>
        /// Test the property 'SuccessorRef'
        /// </summary>
        [Fact]
        public void SuccessorRefTest()
        {
            // TODO unit test for the property 'SuccessorRef'
        }
        /// <summary>
        /// Test the property 'Hierarchy'
        /// </summary>
        [Fact]
        public void HierarchyTest()
        {
            // TODO unit test for the property 'Hierarchy'
        }

    }

}
