/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing CheckResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckResult
        //private CheckResult instance;

        public CheckResultTests()
        {
            // TODO uncomment below to create an instance of CheckResult
            //instance = new CheckResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckResult
        /// </summary>
        [Fact]
        public void CheckResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckResult
            //Assert.IsType<CheckResult>(instance);
        }


        /// <summary>
        /// Test the property 'Check'
        /// </summary>
        [Fact]
        public void CheckTest()
        {
            // TODO unit test for the property 'Check'
        }

    }

}
