/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing ConvertionRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConvertionRecordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConvertionRecord
        //private ConvertionRecord instance;

        public ConvertionRecordTests()
        {
            // TODO uncomment below to create an instance of ConvertionRecord
            //instance = new ConvertionRecord();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConvertionRecord
        /// </summary>
        [Fact]
        public void ConvertionRecordInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConvertionRecord
            //Assert.IsType<ConvertionRecord>(instance);
        }


        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'ExtId'
        /// </summary>
        [Fact]
        public void ExtIdTest()
        {
            // TODO unit test for the property 'ExtId'
        }

    }

}
