/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing ConvertionResultBlockResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConvertionResultBlockResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConvertionResultBlockResult
        //private ConvertionResultBlockResult instance;

        public ConvertionResultBlockResultTests()
        {
            // TODO uncomment below to create an instance of ConvertionResultBlockResult
            //instance = new ConvertionResultBlockResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConvertionResultBlockResult
        /// </summary>
        [Fact]
        public void ConvertionResultBlockResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConvertionResultBlockResult
            //Assert.IsType<ConvertionResultBlockResult>(instance);
        }


        /// <summary>
        /// Test the property 'Block'
        /// </summary>
        [Fact]
        public void BlockTest()
        {
            // TODO unit test for the property 'Block'
        }

    }

}
