/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing ConversionTaskStatusAndStatistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversionTaskStatusAndStatisticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversionTaskStatusAndStatistics
        //private ConversionTaskStatusAndStatistics instance;

        public ConversionTaskStatusAndStatisticsTests()
        {
            // TODO uncomment below to create an instance of ConversionTaskStatusAndStatistics
            //instance = new ConversionTaskStatusAndStatistics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversionTaskStatusAndStatistics
        /// </summary>
        [Fact]
        public void ConversionTaskStatusAndStatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversionTaskStatusAndStatistics
            //Assert.IsType<ConversionTaskStatusAndStatistics>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TotalRecords'
        /// </summary>
        [Fact]
        public void TotalRecordsTest()
        {
            // TODO unit test for the property 'TotalRecords'
        }
        /// <summary>
        /// Test the property 'Processed'
        /// </summary>
        [Fact]
        public void ProcessedTest()
        {
            // TODO unit test for the property 'Processed'
        }
        /// <summary>
        /// Test the property 'Converted'
        /// </summary>
        [Fact]
        public void ConvertedTest()
        {
            // TODO unit test for the property 'Converted'
        }
        /// <summary>
        /// Test the property 'Nonconverted'
        /// </summary>
        [Fact]
        public void NonconvertedTest()
        {
            // TODO unit test for the property 'Nonconverted'
        }
        /// <summary>
        /// Test the property 'BlockCount'
        /// </summary>
        [Fact]
        public void BlockCountTest()
        {
            // TODO unit test for the property 'BlockCount'
        }

    }

}
