/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorResult
        //private ErrorResult instance;

        public ErrorResultTests()
        {
            // TODO uncomment below to create an instance of ErrorResult
            //instance = new ErrorResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorResult
        /// </summary>
        [Fact]
        public void ErrorResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorResult
            //Assert.IsType<ErrorResult>(instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
