/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing FiasType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FiasTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FiasType
        //private FiasType instance;

        public FiasTypeTests()
        {
            // TODO uncomment below to create an instance of FiasType
            //instance = new FiasType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FiasType
        /// </summary>
        [Fact]
        public void FiasTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" FiasType
            //Assert.IsType<FiasType>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AddressLevel'
        /// </summary>
        [Fact]
        public void AddressLevelTest()
        {
            // TODO unit test for the property 'AddressLevel'
        }
        /// <summary>
        /// Test the property 'TypeShortName'
        /// </summary>
        [Fact]
        public void TypeShortNameTest()
        {
            // TODO unit test for the property 'TypeShortName'
        }
        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Fact]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'FormCode'
        /// </summary>
        [Fact]
        public void FormCodeTest()
        {
            // TODO unit test for the property 'FormCode'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

    }

}
