/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing FilterObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterObject
        //private FilterObject instance;

        public FilterObjectTests()
        {
            // TODO uncomment below to create an instance of FilterObject
            //instance = new FilterObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterObject
        /// </summary>
        [Fact]
        public void FilterObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterObject
            //Assert.IsType<FilterObject>(instance);
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'AddressLevel'
        /// </summary>
        [Fact]
        public void AddressLevelTest()
        {
            // TODO unit test for the property 'AddressLevel'
        }
        /// <summary>
        /// Test the property 'AddressLevels'
        /// </summary>
        [Fact]
        public void AddressLevelsTest()
        {
            // TODO unit test for the property 'AddressLevels'
        }
        /// <summary>
        /// Test the property 'NamePart'
        /// </summary>
        [Fact]
        public void NamePartTest()
        {
            // TODO unit test for the property 'NamePart'
        }
        /// <summary>
        /// Test the property 'AddressType'
        /// </summary>
        [Fact]
        public void AddressTypeTest()
        {
            // TODO unit test for the property 'AddressType'
        }
        /// <summary>
        /// Test the property 'IncludeDescendants'
        /// </summary>
        [Fact]
        public void IncludeDescendantsTest()
        {
            // TODO unit test for the property 'IncludeDescendants'
        }

    }

}
