/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing HintResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HintResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HintResult
        //private HintResult instance;

        public HintResultTests()
        {
            // TODO uncomment below to create an instance of HintResult
            //instance = new HintResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HintResult
        /// </summary>
        [Fact]
        public void HintResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" HintResult
            //Assert.IsType<HintResult>(instance);
        }


        /// <summary>
        /// Test the property 'Hints'
        /// </summary>
        [Fact]
        public void HintsTest()
        {
            // TODO unit test for the property 'Hints'
        }

    }

}
