/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing IdResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdResult
        //private IdResult instance;

        public IdResultTests()
        {
            // TODO uncomment below to create an instance of IdResult
            //instance = new IdResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdResult
        /// </summary>
        [Fact]
        public void IdResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdResult
            //Assert.IsType<IdResult>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
