/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing IFetchChangesTaskStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IFetchChangesTaskStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IFetchChangesTaskStatus
        //private IFetchChangesTaskStatus instance;

        public IFetchChangesTaskStatusTests()
        {
            // TODO uncomment below to create an instance of IFetchChangesTaskStatus
            //instance = new IFetchChangesTaskStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IFetchChangesTaskStatus
        /// </summary>
        [Fact]
        public void IFetchChangesTaskStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" IFetchChangesTaskStatus
            //Assert.IsType<IFetchChangesTaskStatus>(instance);
        }


        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Fact]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }
        /// <summary>
        /// Test the property 'BlockCount'
        /// </summary>
        [Fact]
        public void BlockCountTest()
        {
            // TODO unit test for the property 'BlockCount'
        }

    }

}
