/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing NoticeFilterObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NoticeFilterObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NoticeFilterObject
        //private NoticeFilterObject instance;

        public NoticeFilterObjectTests()
        {
            // TODO uncomment below to create an instance of NoticeFilterObject
            //instance = new NoticeFilterObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NoticeFilterObject
        /// </summary>
        [Fact]
        public void NoticeFilterObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" NoticeFilterObject
            //Assert.IsType<NoticeFilterObject>(instance);
        }


        /// <summary>
        /// Test the property 'SenderCode'
        /// </summary>
        [Fact]
        public void SenderCodeTest()
        {
            // TODO unit test for the property 'SenderCode'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ParentObjectGuid'
        /// </summary>
        [Fact]
        public void ParentObjectGuidTest()
        {
            // TODO unit test for the property 'ParentObjectGuid'
        }

    }

}
