/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing NoticeItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NoticeItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NoticeItem
        //private NoticeItem instance;

        public NoticeItemTests()
        {
            // TODO uncomment below to create an instance of NoticeItem
            //instance = new NoticeItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NoticeItem
        /// </summary>
        [Fact]
        public void NoticeItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" NoticeItem
            //Assert.IsType<NoticeItem>(instance);
        }


        /// <summary>
        /// Test the property 'NoticeId'
        /// </summary>
        [Fact]
        public void NoticeIdTest()
        {
            // TODO unit test for the property 'NoticeId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDate'
        /// </summary>
        [Fact]
        public void StatusDateTest()
        {
            // TODO unit test for the property 'StatusDate'
        }
        /// <summary>
        /// Test the property 'Notice'
        /// </summary>
        [Fact]
        public void NoticeTest()
        {
            // TODO unit test for the property 'Notice'
        }

    }

}
