/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing Notice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NoticeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Notice
        //private Notice instance;

        public NoticeTests()
        {
            // TODO uncomment below to create an instance of Notice
            //instance = new Notice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Notice
        /// </summary>
        [Fact]
        public void NoticeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Notice
            //Assert.IsType<Notice>(instance);
        }


        /// <summary>
        /// Test the property 'SenderCode'
        /// </summary>
        [Fact]
        public void SenderCodeTest()
        {
            // TODO unit test for the property 'SenderCode'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Fact]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'NoticeType'
        /// </summary>
        [Fact]
        public void NoticeTypeTest()
        {
            // TODO unit test for the property 'NoticeType'
        }
        /// <summary>
        /// Test the property 'SourceType'
        /// </summary>
        [Fact]
        public void SourceTypeTest()
        {
            // TODO unit test for the property 'SourceType'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'RequestDate'
        /// </summary>
        [Fact]
        public void RequestDateTest()
        {
            // TODO unit test for the property 'RequestDate'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
