/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing ObjectRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObjectRefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObjectRef
        //private ObjectRef instance;

        public ObjectRefTests()
        {
            // TODO uncomment below to create an instance of ObjectRef
            //instance = new ObjectRef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObjectRef
        /// </summary>
        [Fact]
        public void ObjectRefInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObjectRef
            //Assert.IsType<ObjectRef>(instance);
        }


        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Fact]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'ObjectGuid'
        /// </summary>
        [Fact]
        public void ObjectGuidTest()
        {
            // TODO unit test for the property 'ObjectGuid'
        }

    }

}
