/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing SearchByPartsResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchByPartsResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchByPartsResult
        //private SearchByPartsResult instance;

        public SearchByPartsResultTests()
        {
            // TODO uncomment below to create an instance of SearchByPartsResult
            //instance = new SearchByPartsResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchByPartsResult
        /// </summary>
        [Fact]
        public void SearchByPartsResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchByPartsResult
            //Assert.IsType<SearchByPartsResult>(instance);
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AddressItem'
        /// </summary>
        [Fact]
        public void AddressItemTest()
        {
            // TODO unit test for the property 'AddressItem'
        }
        /// <summary>
        /// Test the property 'LastFoundItem'
        /// </summary>
        [Fact]
        public void LastFoundItemTest()
        {
            // TODO unit test for the property 'LastFoundItem'
        }

    }

}
