/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FIASCo.Model;
using FIASCo.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FIASCo.Test.Model
{
    /// <summary>
    ///  Class for testing StructuredAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructuredAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StructuredAddress
        //private StructuredAddress instance;

        public StructuredAddressTests()
        {
            // TODO uncomment below to create an instance of StructuredAddress
            //instance = new StructuredAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StructuredAddress
        /// </summary>
        [Fact]
        public void StructuredAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" StructuredAddress
            //Assert.IsType<StructuredAddress>(instance);
        }


        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'District'
        /// </summary>
        [Fact]
        public void DistrictTest()
        {
            // TODO unit test for the property 'District'
        }
        /// <summary>
        /// Test the property 'CitySettlement'
        /// </summary>
        [Fact]
        public void CitySettlementTest()
        {
            // TODO unit test for the property 'CitySettlement'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Settlement'
        /// </summary>
        [Fact]
        public void SettlementTest()
        {
            // TODO unit test for the property 'Settlement'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'PlanningStructure'
        /// </summary>
        [Fact]
        public void PlanningStructureTest()
        {
            // TODO unit test for the property 'PlanningStructure'
        }
        /// <summary>
        /// Test the property 'House'
        /// </summary>
        [Fact]
        public void HouseTest()
        {
            // TODO unit test for the property 'House'
        }
        /// <summary>
        /// Test the property 'Building'
        /// </summary>
        [Fact]
        public void BuildingTest()
        {
            // TODO unit test for the property 'Building'
        }
        /// <summary>
        /// Test the property 'Flat'
        /// </summary>
        [Fact]
        public void FlatTest()
        {
            // TODO unit test for the property 'Flat'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'KladrCode'
        /// </summary>
        [Fact]
        public void KladrCodeTest()
        {
            // TODO unit test for the property 'KladrCode'
        }
        /// <summary>
        /// Test the property 'ObjectLevelId'
        /// </summary>
        [Fact]
        public void ObjectLevelIdTest()
        {
            // TODO unit test for the property 'ObjectLevelId'
        }

    }

}
