/*
 * SPAS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FIASCo.Client.OpenAPIDateConverter;

namespace FIASCo.Model
{
    /// <summary>
    /// Результат возвращающий идентификатор уведомления
    /// </summary>
    [DataContract(Name = "AddNoticeResult")]
    public partial class AddNoticeResult : IEquatable<AddNoticeResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddNoticeResult" /> class.
        /// </summary>
        /// <param name="noticeId">Идентификатор уведомления.</param>
        public AddNoticeResult(long noticeId = default(long))
        {
            this.NoticeId = noticeId;
        }

        /// <summary>
        /// Идентификатор уведомления
        /// </summary>
        /// <value>Идентификатор уведомления</value>
        [DataMember(Name = "notice_id", EmitDefaultValue = false)]
        public long NoticeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddNoticeResult {\n");
            sb.Append("  NoticeId: ").Append(NoticeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddNoticeResult);
        }

        /// <summary>
        /// Returns true if AddNoticeResult instances are equal
        /// </summary>
        /// <param name="input">Instance of AddNoticeResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddNoticeResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NoticeId == input.NoticeId ||
                    this.NoticeId.Equals(input.NoticeId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.NoticeId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
